version: '3.8'

services:
  vprofile:
    build:
      context: ./vprofile
    container_name: vp1
    ports:
      - "8080:8080"

  JWC:
    build:
      context: ./JWC
    container_name: javawebcalculator
    ports:
      - "8081:8080"
